/* File: sigwfastmodule.c
 * This file is auto-generated with f2py (version:1.26.4).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Fri Mar 14 13:57:31 2025
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *sigwfast_error;
static PyObject *sigwfast_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/

/* See fortranobject.h for definitions. The macros here are provided for BC. */
#define rank f2py_rank
#define shape f2py_shape
#define fshape f2py_shape
#define len f2py_len
#define flen f2py_flen
#define slen f2py_slen
#define size f2py_size


#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif


#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(sigwfast_error,errstring);\
        /*goto capi_fail;*/\
    } else 

#define CHECKARRAY(check,tcheck,name) \
    if (!(check)) {\
        PyErr_SetString(sigwfast_error,"("tcheck") failed for "name);\
        /*goto capi_fail;*/\
    } else 

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/

static int
double_from_pyobj(double* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
        *v = PyFloat_AsDouble(obj);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    tmp = PyNumber_Float(obj);
    if (tmp) {
        *v = PyFloat_AsDouble(tmp);
        Py_DECREF(tmp);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = sigwfast_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }

    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = sigwfast_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/****************************** power_spectrum_k ******************************/
static char doc_f2py_rout_sigwfast_sigwfast_mod_power_spectrum_k[] = "\
y = power_spectrum_k(nodes,vals,k)\n\nWrapper for ``power_spectrum_k``.\
\n\nParameters\n----------\n"
"nodes : input rank-1 array('d') with bounds (f2py_nodes_d0)\n"
"vals : input rank-1 array('d') with bounds (f2py_vals_d0)\n"
"k : input float\n"
"\nReturns\n-------\n"
"y : float";
/* #declfortranroutine# */
static PyObject *f2py_rout_sigwfast_sigwfast_mod_power_spectrum_k(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double power_spectrum_kf2pywrap = 0;
    double *nodes = NULL;
    npy_intp nodes_Dims[1] = {-1};
    const int nodes_Rank = 1;
    PyArrayObject *capi_nodes_as_array = NULL;
    int capi_nodes_intent = 0;
    PyObject *nodes_capi = Py_None;
    double *vals = NULL;
    npy_intp vals_Dims[1] = {-1};
    const int vals_Rank = 1;
    PyArrayObject *capi_vals_as_array = NULL;
    int capi_vals_intent = 0;
    PyObject *vals_capi = Py_None;
    double k = 0;
    PyObject *k_capi = Py_None;
    int f2py_nodes_d0 = 0;
    int f2py_vals_d0 = 0;
    static char *capi_kwlist[] = {"nodes","vals","k",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOO|:sigwfast.sigwfast_mod.power_spectrum_k",\
        capi_kwlist,&nodes_capi,&vals_capi,&k_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable k */
        f2py_success = double_from_pyobj(&k,k_capi,"sigwfast.sigwfast_mod.power_spectrum_k() 3rd argument (k) can't be converted to double");
    if (f2py_success) {
    /* Processing variable nodes */
    ;
    capi_nodes_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.power_spectrum_k: failed to create array from the 1st argument `nodes`";
    capi_nodes_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,nodes_Dims,nodes_Rank,  capi_nodes_intent,nodes_capi,capi_errmess);
    if (capi_nodes_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        nodes = (double *)(PyArray_DATA(capi_nodes_as_array));

    /* Processing variable vals */
    ;
    capi_vals_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.power_spectrum_k: failed to create array from the 2nd argument `vals`";
    capi_vals_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,vals_Dims,vals_Rank,  capi_vals_intent,vals_capi,capi_errmess);
    if (capi_vals_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        vals = (double *)(PyArray_DATA(capi_vals_as_array));

    /* Processing variable power_spectrum_kf2pywrap */
    /* Processing variable f2py_nodes_d0 */
    f2py_nodes_d0 = shape(nodes, 0);
    /* Processing variable f2py_vals_d0 */
    f2py_vals_d0 = shape(vals, 0);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(&power_spectrum_kf2pywrap,nodes,vals,&k,&f2py_nodes_d0,&f2py_vals_d0);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("d",power_spectrum_kf2pywrap);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable f2py_vals_d0 */
    /* End of cleaning variable f2py_nodes_d0 */
    /* End of cleaning variable power_spectrum_kf2pywrap */
    if((PyObject *)capi_vals_as_array!=vals_capi) {
        Py_XDECREF(capi_vals_as_array); }
    }  /* if (capi_vals_as_array == NULL) ... else of vals */
    /* End of cleaning variable vals */
    if((PyObject *)capi_nodes_as_array!=nodes_capi) {
        Py_XDECREF(capi_nodes_as_array); }
    }  /* if (capi_nodes_as_array == NULL) ... else of nodes */
    /* End of cleaning variable nodes */
    } /*if (f2py_success) of k*/
    /* End of cleaning variable k */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/************************** end of power_spectrum_k **************************/

/*************************** power_spectrum_k_array ***************************/
static char doc_f2py_rout_sigwfast_sigwfast_mod_power_spectrum_k_array[] = "\
y = power_spectrum_k_array(nodes,vals,k)\n\nWrapper for ``power_spectrum_k_array``.\
\n\nParameters\n----------\n"
"nodes : input rank-1 array('d') with bounds (f2py_nodes_d0)\n"
"vals : input rank-1 array('d') with bounds (f2py_vals_d0)\n"
"k : input rank-1 array('d') with bounds (f2py_k_d0)\n"
"\nReturns\n-------\n"
"y : rank-1 array('d') with bounds (size(k)) and power_spectrum_k_arrayf2pywrap storage";
/* #declfortranroutine# */
static PyObject *f2py_rout_sigwfast_sigwfast_mod_power_spectrum_k_array(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double *power_spectrum_k_arrayf2pywrap = NULL;
    npy_intp power_spectrum_k_arrayf2pywrap_Dims[1] = {-1};
    const int power_spectrum_k_arrayf2pywrap_Rank = 1;
    PyArrayObject *capi_power_spectrum_k_arrayf2pywrap_as_array = NULL;
    int capi_power_spectrum_k_arrayf2pywrap_intent = 0;
    double *nodes = NULL;
    npy_intp nodes_Dims[1] = {-1};
    const int nodes_Rank = 1;
    PyArrayObject *capi_nodes_as_array = NULL;
    int capi_nodes_intent = 0;
    PyObject *nodes_capi = Py_None;
    double *vals = NULL;
    npy_intp vals_Dims[1] = {-1};
    const int vals_Rank = 1;
    PyArrayObject *capi_vals_as_array = NULL;
    int capi_vals_intent = 0;
    PyObject *vals_capi = Py_None;
    double *k = NULL;
    npy_intp k_Dims[1] = {-1};
    const int k_Rank = 1;
    PyArrayObject *capi_k_as_array = NULL;
    int capi_k_intent = 0;
    PyObject *k_capi = Py_None;
    int f2py_nodes_d0 = 0;
    int f2py_vals_d0 = 0;
    int f2py_k_d0 = 0;
    static char *capi_kwlist[] = {"nodes","vals","k",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOO|:sigwfast.sigwfast_mod.power_spectrum_k_array",\
        capi_kwlist,&nodes_capi,&vals_capi,&k_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable k */
    ;
    capi_k_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.power_spectrum_k_array: failed to create array from the 3rd argument `k`";
    capi_k_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,k_Dims,k_Rank,  capi_k_intent,k_capi,capi_errmess);
    if (capi_k_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        k = (double *)(PyArray_DATA(capi_k_as_array));

    /* Processing variable nodes */
    ;
    capi_nodes_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.power_spectrum_k_array: failed to create array from the 1st argument `nodes`";
    capi_nodes_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,nodes_Dims,nodes_Rank,  capi_nodes_intent,nodes_capi,capi_errmess);
    if (capi_nodes_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        nodes = (double *)(PyArray_DATA(capi_nodes_as_array));

    /* Processing variable vals */
    ;
    capi_vals_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.power_spectrum_k_array: failed to create array from the 2nd argument `vals`";
    capi_vals_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,vals_Dims,vals_Rank,  capi_vals_intent,vals_capi,capi_errmess);
    if (capi_vals_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        vals = (double *)(PyArray_DATA(capi_vals_as_array));

    /* Processing variable power_spectrum_k_arrayf2pywrap */
    power_spectrum_k_arrayf2pywrap_Dims[0]=size(k);
    capi_power_spectrum_k_arrayf2pywrap_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.power_spectrum_k_array: failed to create array from the hidden `power_spectrum_k_arrayf2pywrap`";
    capi_power_spectrum_k_arrayf2pywrap_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,power_spectrum_k_arrayf2pywrap_Dims,power_spectrum_k_arrayf2pywrap_Rank,  capi_power_spectrum_k_arrayf2pywrap_intent,Py_None,capi_errmess);
    if (capi_power_spectrum_k_arrayf2pywrap_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        power_spectrum_k_arrayf2pywrap = (double *)(PyArray_DATA(capi_power_spectrum_k_arrayf2pywrap_as_array));

    /* Processing variable f2py_nodes_d0 */
    f2py_nodes_d0 = shape(nodes, 0);
    /* Processing variable f2py_vals_d0 */
    f2py_vals_d0 = shape(vals, 0);
    /* Processing variable f2py_k_d0 */
    f2py_k_d0 = shape(k, 0);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(power_spectrum_k_arrayf2pywrap,nodes,vals,k,&f2py_nodes_d0,&f2py_vals_d0,&f2py_k_d0);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_power_spectrum_k_arrayf2pywrap_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable f2py_k_d0 */
    /* End of cleaning variable f2py_vals_d0 */
    /* End of cleaning variable f2py_nodes_d0 */
    }  /* if (capi_power_spectrum_k_arrayf2pywrap_as_array == NULL) ... else of power_spectrum_k_arrayf2pywrap */
    /* End of cleaning variable power_spectrum_k_arrayf2pywrap */
    if((PyObject *)capi_vals_as_array!=vals_capi) {
        Py_XDECREF(capi_vals_as_array); }
    }  /* if (capi_vals_as_array == NULL) ... else of vals */
    /* End of cleaning variable vals */
    if((PyObject *)capi_nodes_as_array!=nodes_capi) {
        Py_XDECREF(capi_nodes_as_array); }
    }  /* if (capi_nodes_as_array == NULL) ... else of nodes */
    /* End of cleaning variable nodes */
    if((PyObject *)capi_k_as_array!=k_capi) {
        Py_XDECREF(capi_k_as_array); }
    }  /* if (capi_k_as_array == NULL) ... else of k */
    /* End of cleaning variable k */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*********************** end of power_spectrum_k_array ***********************/

/********************************** psquared **********************************/
static char doc_f2py_rout_sigwfast_sigwfast_mod_psquared[] = "\
y = psquared(nodes,vals,d,s,k)\n\nWrapper for ``psquared``.\
\n\nParameters\n----------\n"
"nodes : input rank-1 array('d') with bounds (f2py_nodes_d0)\n"
"vals : input rank-1 array('d') with bounds (f2py_vals_d0)\n"
"d : input rank-1 array('d') with bounds (f2py_d_d0)\n"
"s : input rank-1 array('d') with bounds (f2py_s_d0)\n"
"k : input float\n"
"\nReturns\n-------\n"
"y : rank-1 array('d') with bounds (size(d)) and psquaredf2pywrap storage";
/* #declfortranroutine# */
static PyObject *f2py_rout_sigwfast_sigwfast_mod_psquared(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,double*,double*,int*,int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double *psquaredf2pywrap = NULL;
    npy_intp psquaredf2pywrap_Dims[1] = {-1};
    const int psquaredf2pywrap_Rank = 1;
    PyArrayObject *capi_psquaredf2pywrap_as_array = NULL;
    int capi_psquaredf2pywrap_intent = 0;
    double *nodes = NULL;
    npy_intp nodes_Dims[1] = {-1};
    const int nodes_Rank = 1;
    PyArrayObject *capi_nodes_as_array = NULL;
    int capi_nodes_intent = 0;
    PyObject *nodes_capi = Py_None;
    double *vals = NULL;
    npy_intp vals_Dims[1] = {-1};
    const int vals_Rank = 1;
    PyArrayObject *capi_vals_as_array = NULL;
    int capi_vals_intent = 0;
    PyObject *vals_capi = Py_None;
    double *d = NULL;
    npy_intp d_Dims[1] = {-1};
    const int d_Rank = 1;
    PyArrayObject *capi_d_as_array = NULL;
    int capi_d_intent = 0;
    PyObject *d_capi = Py_None;
    double *s = NULL;
    npy_intp s_Dims[1] = {-1};
    const int s_Rank = 1;
    PyArrayObject *capi_s_as_array = NULL;
    int capi_s_intent = 0;
    PyObject *s_capi = Py_None;
    double k = 0;
    PyObject *k_capi = Py_None;
    int f2py_nodes_d0 = 0;
    int f2py_vals_d0 = 0;
    int f2py_d_d0 = 0;
    int f2py_s_d0 = 0;
    static char *capi_kwlist[] = {"nodes","vals","d","s","k",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOO|:sigwfast.sigwfast_mod.psquared",\
        capi_kwlist,&nodes_capi,&vals_capi,&d_capi,&s_capi,&k_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable nodes */
    ;
    capi_nodes_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.psquared: failed to create array from the 1st argument `nodes`";
    capi_nodes_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,nodes_Dims,nodes_Rank,  capi_nodes_intent,nodes_capi,capi_errmess);
    if (capi_nodes_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        nodes = (double *)(PyArray_DATA(capi_nodes_as_array));

    /* Processing variable vals */
    ;
    capi_vals_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.psquared: failed to create array from the 2nd argument `vals`";
    capi_vals_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,vals_Dims,vals_Rank,  capi_vals_intent,vals_capi,capi_errmess);
    if (capi_vals_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        vals = (double *)(PyArray_DATA(capi_vals_as_array));

    /* Processing variable d */
    ;
    capi_d_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.psquared: failed to create array from the 3rd argument `d`";
    capi_d_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,d_Dims,d_Rank,  capi_d_intent,d_capi,capi_errmess);
    if (capi_d_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        d = (double *)(PyArray_DATA(capi_d_as_array));

    /* Processing variable s */
    ;
    capi_s_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.psquared: failed to create array from the 4th argument `s`";
    capi_s_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,s_Dims,s_Rank,  capi_s_intent,s_capi,capi_errmess);
    if (capi_s_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        s = (double *)(PyArray_DATA(capi_s_as_array));

    /* Processing variable k */
        f2py_success = double_from_pyobj(&k,k_capi,"sigwfast.sigwfast_mod.psquared() 5th argument (k) can't be converted to double");
    if (f2py_success) {
    /* Processing variable psquaredf2pywrap */
    psquaredf2pywrap_Dims[0]=size(d);
    capi_psquaredf2pywrap_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.psquared: failed to create array from the hidden `psquaredf2pywrap`";
    capi_psquaredf2pywrap_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,psquaredf2pywrap_Dims,psquaredf2pywrap_Rank,  capi_psquaredf2pywrap_intent,Py_None,capi_errmess);
    if (capi_psquaredf2pywrap_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        psquaredf2pywrap = (double *)(PyArray_DATA(capi_psquaredf2pywrap_as_array));

    /* Processing variable f2py_nodes_d0 */
    f2py_nodes_d0 = shape(nodes, 0);
    /* Processing variable f2py_vals_d0 */
    f2py_vals_d0 = shape(vals, 0);
    /* Processing variable f2py_d_d0 */
    f2py_d_d0 = shape(d, 0);
    /* Processing variable f2py_s_d0 */
    f2py_s_d0 = shape(s, 0);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(psquaredf2pywrap,nodes,vals,d,s,&k,&f2py_nodes_d0,&f2py_vals_d0,&f2py_d_d0,&f2py_s_d0);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_psquaredf2pywrap_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable f2py_s_d0 */
    /* End of cleaning variable f2py_d_d0 */
    /* End of cleaning variable f2py_vals_d0 */
    /* End of cleaning variable f2py_nodes_d0 */
    }  /* if (capi_psquaredf2pywrap_as_array == NULL) ... else of psquaredf2pywrap */
    /* End of cleaning variable psquaredf2pywrap */
    } /*if (f2py_success) of k*/
    /* End of cleaning variable k */
    if((PyObject *)capi_s_as_array!=s_capi) {
        Py_XDECREF(capi_s_as_array); }
    }  /* if (capi_s_as_array == NULL) ... else of s */
    /* End of cleaning variable s */
    if((PyObject *)capi_d_as_array!=d_capi) {
        Py_XDECREF(capi_d_as_array); }
    }  /* if (capi_d_as_array == NULL) ... else of d */
    /* End of cleaning variable d */
    if((PyObject *)capi_vals_as_array!=vals_capi) {
        Py_XDECREF(capi_vals_as_array); }
    }  /* if (capi_vals_as_array == NULL) ... else of vals */
    /* End of cleaning variable vals */
    if((PyObject *)capi_nodes_as_array!=nodes_capi) {
        Py_XDECREF(capi_nodes_as_array); }
    }  /* if (capi_nodes_as_array == NULL) ... else of nodes */
    /* End of cleaning variable nodes */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************************** end of psquared ******************************/

/******************************** compute_w_k ********************************/
static char doc_f2py_rout_sigwfast_sigwfast_mod_compute_w_k[] = "\
y_k = compute_w_k(nodes,vals,k,kernel1,kernel2,d1array,s1array,d2array,s2array,darray,nd,ns1,ns2)\n\nWrapper for ``compute_w_k``.\
\n\nParameters\n----------\n"
"nodes : input rank-1 array('d') with bounds (f2py_nodes_d0)\n"
"vals : input rank-1 array('d') with bounds (f2py_vals_d0)\n"
"k : input float\n"
"kernel1 : input rank-1 array('d') with bounds (nd * ns1)\n"
"kernel2 : input rank-1 array('d') with bounds (nd * ns2)\n"
"d1array : input rank-1 array('d') with bounds (nd * ns1)\n"
"s1array : input rank-1 array('d') with bounds (nd * ns1)\n"
"d2array : input rank-1 array('d') with bounds (nd * ns2)\n"
"s2array : input rank-1 array('d') with bounds (nd * ns2)\n"
"darray : input rank-1 array('d') with bounds (nd)\n"
"nd : input int, optional\n    Default: shape(darray, 0)\n"
"ns1 : input int\n"
"ns2 : input int\n"
"\nReturns\n-------\n"
"y_k : float";
/* #declfortranroutine# */
static PyObject *f2py_rout_sigwfast_sigwfast_mod_compute_w_k(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,int*,int*,int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double compute_w_kf2pywrap = 0;
    double *nodes = NULL;
    npy_intp nodes_Dims[1] = {-1};
    const int nodes_Rank = 1;
    PyArrayObject *capi_nodes_as_array = NULL;
    int capi_nodes_intent = 0;
    PyObject *nodes_capi = Py_None;
    double *vals = NULL;
    npy_intp vals_Dims[1] = {-1};
    const int vals_Rank = 1;
    PyArrayObject *capi_vals_as_array = NULL;
    int capi_vals_intent = 0;
    PyObject *vals_capi = Py_None;
    double k = 0;
    PyObject *k_capi = Py_None;
    double *kernel1 = NULL;
    npy_intp kernel1_Dims[1] = {-1};
    const int kernel1_Rank = 1;
    PyArrayObject *capi_kernel1_as_array = NULL;
    int capi_kernel1_intent = 0;
    PyObject *kernel1_capi = Py_None;
    double *kernel2 = NULL;
    npy_intp kernel2_Dims[1] = {-1};
    const int kernel2_Rank = 1;
    PyArrayObject *capi_kernel2_as_array = NULL;
    int capi_kernel2_intent = 0;
    PyObject *kernel2_capi = Py_None;
    double *d1array = NULL;
    npy_intp d1array_Dims[1] = {-1};
    const int d1array_Rank = 1;
    PyArrayObject *capi_d1array_as_array = NULL;
    int capi_d1array_intent = 0;
    PyObject *d1array_capi = Py_None;
    double *s1array = NULL;
    npy_intp s1array_Dims[1] = {-1};
    const int s1array_Rank = 1;
    PyArrayObject *capi_s1array_as_array = NULL;
    int capi_s1array_intent = 0;
    PyObject *s1array_capi = Py_None;
    double *d2array = NULL;
    npy_intp d2array_Dims[1] = {-1};
    const int d2array_Rank = 1;
    PyArrayObject *capi_d2array_as_array = NULL;
    int capi_d2array_intent = 0;
    PyObject *d2array_capi = Py_None;
    double *s2array = NULL;
    npy_intp s2array_Dims[1] = {-1};
    const int s2array_Rank = 1;
    PyArrayObject *capi_s2array_as_array = NULL;
    int capi_s2array_intent = 0;
    PyObject *s2array_capi = Py_None;
    double *darray = NULL;
    npy_intp darray_Dims[1] = {-1};
    const int darray_Rank = 1;
    PyArrayObject *capi_darray_as_array = NULL;
    int capi_darray_intent = 0;
    PyObject *darray_capi = Py_None;
    int nd = 0;
    PyObject *nd_capi = Py_None;
    int ns1 = 0;
    PyObject *ns1_capi = Py_None;
    int ns2 = 0;
    PyObject *ns2_capi = Py_None;
    int f2py_nodes_d0 = 0;
    int f2py_vals_d0 = 0;
    static char *capi_kwlist[] = {"nodes","vals","k","kernel1","kernel2","d1array","s1array","d2array","s2array","darray","nd","ns1","ns2",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOOOOOOO|:sigwfast.sigwfast_mod.compute_w_k",\
        capi_kwlist,&nodes_capi,&vals_capi,&k_capi,&kernel1_capi,&kernel2_capi,&d1array_capi,&s1array_capi,&d2array_capi,&s2array_capi,&darray_capi,&nd_capi,&ns1_capi,&ns2_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable ns1 */
        f2py_success = int_from_pyobj(&ns1,ns1_capi,"sigwfast.sigwfast_mod.compute_w_k() 12nd argument (ns1) can't be converted to int");
    if (f2py_success) {
    /* Processing variable ns2 */
        f2py_success = int_from_pyobj(&ns2,ns2_capi,"sigwfast.sigwfast_mod.compute_w_k() 13rd argument (ns2) can't be converted to int");
    if (f2py_success) {
    /* Processing variable k */
        f2py_success = double_from_pyobj(&k,k_capi,"sigwfast.sigwfast_mod.compute_w_k() 3rd argument (k) can't be converted to double");
    if (f2py_success) {
    /* Processing variable nodes */
    ;
    capi_nodes_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.compute_w_k: failed to create array from the 1st argument `nodes`";
    capi_nodes_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,nodes_Dims,nodes_Rank,  capi_nodes_intent,nodes_capi,capi_errmess);
    if (capi_nodes_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        nodes = (double *)(PyArray_DATA(capi_nodes_as_array));

    /* Processing variable vals */
    ;
    capi_vals_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.compute_w_k: failed to create array from the 2nd argument `vals`";
    capi_vals_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,vals_Dims,vals_Rank,  capi_vals_intent,vals_capi,capi_errmess);
    if (capi_vals_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        vals = (double *)(PyArray_DATA(capi_vals_as_array));

    /* Processing variable darray */
    ;
    capi_darray_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.compute_w_k: failed to create array from the 10th argument `darray`";
    capi_darray_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,darray_Dims,darray_Rank,  capi_darray_intent,darray_capi,capi_errmess);
    if (capi_darray_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        darray = (double *)(PyArray_DATA(capi_darray_as_array));

    /* Processing variable nd */
    if (nd_capi == Py_None) nd = shape(darray, 0); else
        f2py_success = int_from_pyobj(&nd,nd_capi,"sigwfast.sigwfast_mod.compute_w_k() 11st argument (nd) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(darray, 0) == nd,"shape(darray, 0) == nd","11st argument nd","compute_w_k:nd=%d",nd) {
    /* Processing variable kernel1 */
    kernel1_Dims[0]=nd * ns1;
    capi_kernel1_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.compute_w_k: failed to create array from the 4th argument `kernel1`";
    capi_kernel1_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,kernel1_Dims,kernel1_Rank,  capi_kernel1_intent,kernel1_capi,capi_errmess);
    if (capi_kernel1_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        kernel1 = (double *)(PyArray_DATA(capi_kernel1_as_array));

    CHECKARRAY(shape(kernel1, 0) == nd * ns1,"shape(kernel1, 0) == nd * ns1","4th argument kernel1") {
    CHECKARRAY(shape(kernel1, 0) == nd * ns1,"shape(kernel1, 0) == nd * ns1","4th argument kernel1") {
    /* Processing variable kernel2 */
    kernel2_Dims[0]=nd * ns2;
    capi_kernel2_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.compute_w_k: failed to create array from the 5th argument `kernel2`";
    capi_kernel2_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,kernel2_Dims,kernel2_Rank,  capi_kernel2_intent,kernel2_capi,capi_errmess);
    if (capi_kernel2_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        kernel2 = (double *)(PyArray_DATA(capi_kernel2_as_array));

    CHECKARRAY(shape(kernel2, 0) == nd * ns2,"shape(kernel2, 0) == nd * ns2","5th argument kernel2") {
    CHECKARRAY(shape(kernel2, 0) == nd * ns2,"shape(kernel2, 0) == nd * ns2","5th argument kernel2") {
    /* Processing variable d1array */
    d1array_Dims[0]=nd * ns1;
    capi_d1array_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.compute_w_k: failed to create array from the 6th argument `d1array`";
    capi_d1array_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,d1array_Dims,d1array_Rank,  capi_d1array_intent,d1array_capi,capi_errmess);
    if (capi_d1array_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        d1array = (double *)(PyArray_DATA(capi_d1array_as_array));

    CHECKARRAY(shape(d1array, 0) == nd * ns1,"shape(d1array, 0) == nd * ns1","6th argument d1array") {
    CHECKARRAY(shape(d1array, 0) == nd * ns1,"shape(d1array, 0) == nd * ns1","6th argument d1array") {
    /* Processing variable s1array */
    s1array_Dims[0]=nd * ns1;
    capi_s1array_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.compute_w_k: failed to create array from the 7th argument `s1array`";
    capi_s1array_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,s1array_Dims,s1array_Rank,  capi_s1array_intent,s1array_capi,capi_errmess);
    if (capi_s1array_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        s1array = (double *)(PyArray_DATA(capi_s1array_as_array));

    CHECKARRAY(shape(s1array, 0) == nd * ns1,"shape(s1array, 0) == nd * ns1","7th argument s1array") {
    CHECKARRAY(shape(s1array, 0) == nd * ns1,"shape(s1array, 0) == nd * ns1","7th argument s1array") {
    /* Processing variable d2array */
    d2array_Dims[0]=nd * ns2;
    capi_d2array_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.compute_w_k: failed to create array from the 8th argument `d2array`";
    capi_d2array_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,d2array_Dims,d2array_Rank,  capi_d2array_intent,d2array_capi,capi_errmess);
    if (capi_d2array_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        d2array = (double *)(PyArray_DATA(capi_d2array_as_array));

    CHECKARRAY(shape(d2array, 0) == nd * ns2,"shape(d2array, 0) == nd * ns2","8th argument d2array") {
    CHECKARRAY(shape(d2array, 0) == nd * ns2,"shape(d2array, 0) == nd * ns2","8th argument d2array") {
    /* Processing variable s2array */
    s2array_Dims[0]=nd * ns2;
    capi_s2array_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.compute_w_k: failed to create array from the 9th argument `s2array`";
    capi_s2array_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,s2array_Dims,s2array_Rank,  capi_s2array_intent,s2array_capi,capi_errmess);
    if (capi_s2array_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        s2array = (double *)(PyArray_DATA(capi_s2array_as_array));

    CHECKARRAY(shape(s2array, 0) == nd * ns2,"shape(s2array, 0) == nd * ns2","9th argument s2array") {
    CHECKARRAY(shape(s2array, 0) == nd * ns2,"shape(s2array, 0) == nd * ns2","9th argument s2array") {
    /* Processing variable compute_w_kf2pywrap */
    /* Processing variable f2py_nodes_d0 */
    f2py_nodes_d0 = shape(nodes, 0);
    /* Processing variable f2py_vals_d0 */
    f2py_vals_d0 = shape(vals, 0);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(&compute_w_kf2pywrap,nodes,vals,&k,kernel1,kernel2,d1array,s1array,d2array,s2array,darray,&nd,&ns1,&ns2,&f2py_nodes_d0,&f2py_vals_d0);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("d",compute_w_kf2pywrap);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable f2py_vals_d0 */
    /* End of cleaning variable f2py_nodes_d0 */
    /* End of cleaning variable compute_w_kf2pywrap */
    } /*CHECKARRAY(shape(s2array, 0) == nd * ns2)*/
    } /*CHECKARRAY(shape(s2array, 0) == nd * ns2)*/
    if((PyObject *)capi_s2array_as_array!=s2array_capi) {
        Py_XDECREF(capi_s2array_as_array); }
    }  /* if (capi_s2array_as_array == NULL) ... else of s2array */
    /* End of cleaning variable s2array */
    } /*CHECKARRAY(shape(d2array, 0) == nd * ns2)*/
    } /*CHECKARRAY(shape(d2array, 0) == nd * ns2)*/
    if((PyObject *)capi_d2array_as_array!=d2array_capi) {
        Py_XDECREF(capi_d2array_as_array); }
    }  /* if (capi_d2array_as_array == NULL) ... else of d2array */
    /* End of cleaning variable d2array */
    } /*CHECKARRAY(shape(s1array, 0) == nd * ns1)*/
    } /*CHECKARRAY(shape(s1array, 0) == nd * ns1)*/
    if((PyObject *)capi_s1array_as_array!=s1array_capi) {
        Py_XDECREF(capi_s1array_as_array); }
    }  /* if (capi_s1array_as_array == NULL) ... else of s1array */
    /* End of cleaning variable s1array */
    } /*CHECKARRAY(shape(d1array, 0) == nd * ns1)*/
    } /*CHECKARRAY(shape(d1array, 0) == nd * ns1)*/
    if((PyObject *)capi_d1array_as_array!=d1array_capi) {
        Py_XDECREF(capi_d1array_as_array); }
    }  /* if (capi_d1array_as_array == NULL) ... else of d1array */
    /* End of cleaning variable d1array */
    } /*CHECKARRAY(shape(kernel2, 0) == nd * ns2)*/
    } /*CHECKARRAY(shape(kernel2, 0) == nd * ns2)*/
    if((PyObject *)capi_kernel2_as_array!=kernel2_capi) {
        Py_XDECREF(capi_kernel2_as_array); }
    }  /* if (capi_kernel2_as_array == NULL) ... else of kernel2 */
    /* End of cleaning variable kernel2 */
    } /*CHECKARRAY(shape(kernel1, 0) == nd * ns1)*/
    } /*CHECKARRAY(shape(kernel1, 0) == nd * ns1)*/
    if((PyObject *)capi_kernel1_as_array!=kernel1_capi) {
        Py_XDECREF(capi_kernel1_as_array); }
    }  /* if (capi_kernel1_as_array == NULL) ... else of kernel1 */
    /* End of cleaning variable kernel1 */
    } /*CHECKSCALAR(shape(darray, 0) == nd)*/
    } /*if (f2py_success) of nd*/
    /* End of cleaning variable nd */
    if((PyObject *)capi_darray_as_array!=darray_capi) {
        Py_XDECREF(capi_darray_as_array); }
    }  /* if (capi_darray_as_array == NULL) ... else of darray */
    /* End of cleaning variable darray */
    if((PyObject *)capi_vals_as_array!=vals_capi) {
        Py_XDECREF(capi_vals_as_array); }
    }  /* if (capi_vals_as_array == NULL) ... else of vals */
    /* End of cleaning variable vals */
    if((PyObject *)capi_nodes_as_array!=nodes_capi) {
        Py_XDECREF(capi_nodes_as_array); }
    }  /* if (capi_nodes_as_array == NULL) ... else of nodes */
    /* End of cleaning variable nodes */
    } /*if (f2py_success) of k*/
    /* End of cleaning variable k */
    } /*if (f2py_success) of ns2*/
    /* End of cleaning variable ns2 */
    } /*if (f2py_success) of ns1*/
    /* End of cleaning variable ns1 */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************************** end of compute_w_k *****************************/

/***************************** compute_w_k_array *****************************/
static char doc_f2py_rout_sigwfast_sigwfast_mod_compute_w_k_array[] = "\
integral = compute_w_k_array(nodes,vals,komega,kernel1,kernel2,d1array,s1array,d2array,s2array,darray,nd,ns1,ns2,[nk])\n\nWrapper for ``compute_w_k_array``.\
\n\nParameters\n----------\n"
"nodes : input rank-1 array('d') with bounds (f2py_nodes_d0)\n"
"vals : input rank-1 array('d') with bounds (f2py_vals_d0)\n"
"komega : input rank-1 array('d') with bounds (nk)\n"
"kernel1 : input rank-1 array('d') with bounds (nd * ns1)\n"
"kernel2 : input rank-1 array('d') with bounds (nd * ns2)\n"
"d1array : input rank-1 array('d') with bounds (nd * ns1)\n"
"s1array : input rank-1 array('d') with bounds (nd * ns1)\n"
"d2array : input rank-1 array('d') with bounds (nd * ns2)\n"
"s2array : input rank-1 array('d') with bounds (nd * ns2)\n"
"darray : input rank-1 array('d') with bounds (nd)\n"
"nd : input int, optional\n    Default: shape(darray, 0)\n"
"ns1 : input int\n"
"ns2 : input int\n"
"\nOther Parameters\n----------------\n"
"nk : input int, optional\n    Default: shape(komega, 0)\n"
"\nReturns\n-------\n"
"integral : rank-1 array('d') with bounds (nk)";
/* #declfortranroutine# */
static PyObject *f2py_rout_sigwfast_sigwfast_mod_compute_w_k_array(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,int*,double*,double*,double*,double*,double*,double*,double*,double*,int*,int*,int*,double*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double *nodes = NULL;
    npy_intp nodes_Dims[1] = {-1};
    const int nodes_Rank = 1;
    PyArrayObject *capi_nodes_as_array = NULL;
    int capi_nodes_intent = 0;
    PyObject *nodes_capi = Py_None;
    double *vals = NULL;
    npy_intp vals_Dims[1] = {-1};
    const int vals_Rank = 1;
    PyArrayObject *capi_vals_as_array = NULL;
    int capi_vals_intent = 0;
    PyObject *vals_capi = Py_None;
    int nk = 0;
    PyObject *nk_capi = Py_None;
    double *komega = NULL;
    npy_intp komega_Dims[1] = {-1};
    const int komega_Rank = 1;
    PyArrayObject *capi_komega_as_array = NULL;
    int capi_komega_intent = 0;
    PyObject *komega_capi = Py_None;
    double *kernel1 = NULL;
    npy_intp kernel1_Dims[1] = {-1};
    const int kernel1_Rank = 1;
    PyArrayObject *capi_kernel1_as_array = NULL;
    int capi_kernel1_intent = 0;
    PyObject *kernel1_capi = Py_None;
    double *kernel2 = NULL;
    npy_intp kernel2_Dims[1] = {-1};
    const int kernel2_Rank = 1;
    PyArrayObject *capi_kernel2_as_array = NULL;
    int capi_kernel2_intent = 0;
    PyObject *kernel2_capi = Py_None;
    double *d1array = NULL;
    npy_intp d1array_Dims[1] = {-1};
    const int d1array_Rank = 1;
    PyArrayObject *capi_d1array_as_array = NULL;
    int capi_d1array_intent = 0;
    PyObject *d1array_capi = Py_None;
    double *s1array = NULL;
    npy_intp s1array_Dims[1] = {-1};
    const int s1array_Rank = 1;
    PyArrayObject *capi_s1array_as_array = NULL;
    int capi_s1array_intent = 0;
    PyObject *s1array_capi = Py_None;
    double *d2array = NULL;
    npy_intp d2array_Dims[1] = {-1};
    const int d2array_Rank = 1;
    PyArrayObject *capi_d2array_as_array = NULL;
    int capi_d2array_intent = 0;
    PyObject *d2array_capi = Py_None;
    double *s2array = NULL;
    npy_intp s2array_Dims[1] = {-1};
    const int s2array_Rank = 1;
    PyArrayObject *capi_s2array_as_array = NULL;
    int capi_s2array_intent = 0;
    PyObject *s2array_capi = Py_None;
    double *darray = NULL;
    npy_intp darray_Dims[1] = {-1};
    const int darray_Rank = 1;
    PyArrayObject *capi_darray_as_array = NULL;
    int capi_darray_intent = 0;
    PyObject *darray_capi = Py_None;
    int nd = 0;
    PyObject *nd_capi = Py_None;
    int ns1 = 0;
    PyObject *ns1_capi = Py_None;
    int ns2 = 0;
    PyObject *ns2_capi = Py_None;
    double *integral = NULL;
    npy_intp integral_Dims[1] = {-1};
    const int integral_Rank = 1;
    PyArrayObject *capi_integral_as_array = NULL;
    int capi_integral_intent = 0;
    int f2py_nodes_d0 = 0;
    int f2py_vals_d0 = 0;
    static char *capi_kwlist[] = {"nodes","vals","komega","kernel1","kernel2","d1array","s1array","d2array","s2array","darray","nd","ns1","ns2","nk",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOOOOOOO|O:sigwfast.sigwfast_mod.compute_w_k_array",\
        capi_kwlist,&nodes_capi,&vals_capi,&komega_capi,&kernel1_capi,&kernel2_capi,&d1array_capi,&s1array_capi,&d2array_capi,&s2array_capi,&darray_capi,&nd_capi,&ns1_capi,&ns2_capi,&nk_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable ns1 */
        f2py_success = int_from_pyobj(&ns1,ns1_capi,"sigwfast.sigwfast_mod.compute_w_k_array() 12nd argument (ns1) can't be converted to int");
    if (f2py_success) {
    /* Processing variable ns2 */
        f2py_success = int_from_pyobj(&ns2,ns2_capi,"sigwfast.sigwfast_mod.compute_w_k_array() 13rd argument (ns2) can't be converted to int");
    if (f2py_success) {
    /* Processing variable komega */
    ;
    capi_komega_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.compute_w_k_array: failed to create array from the 3rd argument `komega`";
    capi_komega_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,komega_Dims,komega_Rank,  capi_komega_intent,komega_capi,capi_errmess);
    if (capi_komega_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        komega = (double *)(PyArray_DATA(capi_komega_as_array));

    /* Processing variable nodes */
    ;
    capi_nodes_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.compute_w_k_array: failed to create array from the 1st argument `nodes`";
    capi_nodes_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,nodes_Dims,nodes_Rank,  capi_nodes_intent,nodes_capi,capi_errmess);
    if (capi_nodes_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        nodes = (double *)(PyArray_DATA(capi_nodes_as_array));

    /* Processing variable vals */
    ;
    capi_vals_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.compute_w_k_array: failed to create array from the 2nd argument `vals`";
    capi_vals_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,vals_Dims,vals_Rank,  capi_vals_intent,vals_capi,capi_errmess);
    if (capi_vals_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        vals = (double *)(PyArray_DATA(capi_vals_as_array));

    /* Processing variable darray */
    ;
    capi_darray_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.compute_w_k_array: failed to create array from the 10th argument `darray`";
    capi_darray_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,darray_Dims,darray_Rank,  capi_darray_intent,darray_capi,capi_errmess);
    if (capi_darray_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        darray = (double *)(PyArray_DATA(capi_darray_as_array));

    /* Processing variable nk */
    if (nk_capi == Py_None) nk = shape(komega, 0); else
        f2py_success = int_from_pyobj(&nk,nk_capi,"sigwfast.sigwfast_mod.compute_w_k_array() 1st keyword (nk) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(komega, 0) == nk,"shape(komega, 0) == nk","1st keyword nk","compute_w_k_array:nk=%d",nk) {
    /* Processing variable nd */
    if (nd_capi == Py_None) nd = shape(darray, 0); else
        f2py_success = int_from_pyobj(&nd,nd_capi,"sigwfast.sigwfast_mod.compute_w_k_array() 11st argument (nd) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(darray, 0) == nd,"shape(darray, 0) == nd","11st argument nd","compute_w_k_array:nd=%d",nd) {
    /* Processing variable kernel1 */
    kernel1_Dims[0]=nd * ns1;
    capi_kernel1_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.compute_w_k_array: failed to create array from the 4th argument `kernel1`";
    capi_kernel1_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,kernel1_Dims,kernel1_Rank,  capi_kernel1_intent,kernel1_capi,capi_errmess);
    if (capi_kernel1_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        kernel1 = (double *)(PyArray_DATA(capi_kernel1_as_array));

    CHECKARRAY(shape(kernel1, 0) == nd * ns1,"shape(kernel1, 0) == nd * ns1","4th argument kernel1") {
    CHECKARRAY(shape(kernel1, 0) == nd * ns1,"shape(kernel1, 0) == nd * ns1","4th argument kernel1") {
    /* Processing variable kernel2 */
    kernel2_Dims[0]=nd * ns2;
    capi_kernel2_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.compute_w_k_array: failed to create array from the 5th argument `kernel2`";
    capi_kernel2_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,kernel2_Dims,kernel2_Rank,  capi_kernel2_intent,kernel2_capi,capi_errmess);
    if (capi_kernel2_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        kernel2 = (double *)(PyArray_DATA(capi_kernel2_as_array));

    CHECKARRAY(shape(kernel2, 0) == nd * ns2,"shape(kernel2, 0) == nd * ns2","5th argument kernel2") {
    CHECKARRAY(shape(kernel2, 0) == nd * ns2,"shape(kernel2, 0) == nd * ns2","5th argument kernel2") {
    /* Processing variable d1array */
    d1array_Dims[0]=nd * ns1;
    capi_d1array_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.compute_w_k_array: failed to create array from the 6th argument `d1array`";
    capi_d1array_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,d1array_Dims,d1array_Rank,  capi_d1array_intent,d1array_capi,capi_errmess);
    if (capi_d1array_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        d1array = (double *)(PyArray_DATA(capi_d1array_as_array));

    CHECKARRAY(shape(d1array, 0) == nd * ns1,"shape(d1array, 0) == nd * ns1","6th argument d1array") {
    CHECKARRAY(shape(d1array, 0) == nd * ns1,"shape(d1array, 0) == nd * ns1","6th argument d1array") {
    /* Processing variable s1array */
    s1array_Dims[0]=nd * ns1;
    capi_s1array_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.compute_w_k_array: failed to create array from the 7th argument `s1array`";
    capi_s1array_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,s1array_Dims,s1array_Rank,  capi_s1array_intent,s1array_capi,capi_errmess);
    if (capi_s1array_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        s1array = (double *)(PyArray_DATA(capi_s1array_as_array));

    CHECKARRAY(shape(s1array, 0) == nd * ns1,"shape(s1array, 0) == nd * ns1","7th argument s1array") {
    CHECKARRAY(shape(s1array, 0) == nd * ns1,"shape(s1array, 0) == nd * ns1","7th argument s1array") {
    /* Processing variable d2array */
    d2array_Dims[0]=nd * ns2;
    capi_d2array_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.compute_w_k_array: failed to create array from the 8th argument `d2array`";
    capi_d2array_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,d2array_Dims,d2array_Rank,  capi_d2array_intent,d2array_capi,capi_errmess);
    if (capi_d2array_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        d2array = (double *)(PyArray_DATA(capi_d2array_as_array));

    CHECKARRAY(shape(d2array, 0) == nd * ns2,"shape(d2array, 0) == nd * ns2","8th argument d2array") {
    CHECKARRAY(shape(d2array, 0) == nd * ns2,"shape(d2array, 0) == nd * ns2","8th argument d2array") {
    /* Processing variable s2array */
    s2array_Dims[0]=nd * ns2;
    capi_s2array_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.compute_w_k_array: failed to create array from the 9th argument `s2array`";
    capi_s2array_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,s2array_Dims,s2array_Rank,  capi_s2array_intent,s2array_capi,capi_errmess);
    if (capi_s2array_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        s2array = (double *)(PyArray_DATA(capi_s2array_as_array));

    CHECKARRAY(shape(s2array, 0) == nd * ns2,"shape(s2array, 0) == nd * ns2","9th argument s2array") {
    CHECKARRAY(shape(s2array, 0) == nd * ns2,"shape(s2array, 0) == nd * ns2","9th argument s2array") {
    /* Processing variable integral */
    integral_Dims[0]=nk;
    capi_integral_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.compute_w_k_array: failed to create array from the hidden `integral`";
    capi_integral_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,integral_Dims,integral_Rank,  capi_integral_intent,Py_None,capi_errmess);
    if (capi_integral_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        integral = (double *)(PyArray_DATA(capi_integral_as_array));

    /* Processing variable f2py_nodes_d0 */
    f2py_nodes_d0 = shape(nodes, 0);
    /* Processing variable f2py_vals_d0 */
    f2py_vals_d0 = shape(vals, 0);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(nodes,vals,&nk,komega,kernel1,kernel2,d1array,s1array,d2array,s2array,darray,&nd,&ns1,&ns2,integral,&f2py_nodes_d0,&f2py_vals_d0);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_integral_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable f2py_vals_d0 */
    /* End of cleaning variable f2py_nodes_d0 */
    }  /* if (capi_integral_as_array == NULL) ... else of integral */
    /* End of cleaning variable integral */
    } /*CHECKARRAY(shape(s2array, 0) == nd * ns2)*/
    } /*CHECKARRAY(shape(s2array, 0) == nd * ns2)*/
    if((PyObject *)capi_s2array_as_array!=s2array_capi) {
        Py_XDECREF(capi_s2array_as_array); }
    }  /* if (capi_s2array_as_array == NULL) ... else of s2array */
    /* End of cleaning variable s2array */
    } /*CHECKARRAY(shape(d2array, 0) == nd * ns2)*/
    } /*CHECKARRAY(shape(d2array, 0) == nd * ns2)*/
    if((PyObject *)capi_d2array_as_array!=d2array_capi) {
        Py_XDECREF(capi_d2array_as_array); }
    }  /* if (capi_d2array_as_array == NULL) ... else of d2array */
    /* End of cleaning variable d2array */
    } /*CHECKARRAY(shape(s1array, 0) == nd * ns1)*/
    } /*CHECKARRAY(shape(s1array, 0) == nd * ns1)*/
    if((PyObject *)capi_s1array_as_array!=s1array_capi) {
        Py_XDECREF(capi_s1array_as_array); }
    }  /* if (capi_s1array_as_array == NULL) ... else of s1array */
    /* End of cleaning variable s1array */
    } /*CHECKARRAY(shape(d1array, 0) == nd * ns1)*/
    } /*CHECKARRAY(shape(d1array, 0) == nd * ns1)*/
    if((PyObject *)capi_d1array_as_array!=d1array_capi) {
        Py_XDECREF(capi_d1array_as_array); }
    }  /* if (capi_d1array_as_array == NULL) ... else of d1array */
    /* End of cleaning variable d1array */
    } /*CHECKARRAY(shape(kernel2, 0) == nd * ns2)*/
    } /*CHECKARRAY(shape(kernel2, 0) == nd * ns2)*/
    if((PyObject *)capi_kernel2_as_array!=kernel2_capi) {
        Py_XDECREF(capi_kernel2_as_array); }
    }  /* if (capi_kernel2_as_array == NULL) ... else of kernel2 */
    /* End of cleaning variable kernel2 */
    } /*CHECKARRAY(shape(kernel1, 0) == nd * ns1)*/
    } /*CHECKARRAY(shape(kernel1, 0) == nd * ns1)*/
    if((PyObject *)capi_kernel1_as_array!=kernel1_capi) {
        Py_XDECREF(capi_kernel1_as_array); }
    }  /* if (capi_kernel1_as_array == NULL) ... else of kernel1 */
    /* End of cleaning variable kernel1 */
    } /*CHECKSCALAR(shape(darray, 0) == nd)*/
    } /*if (f2py_success) of nd*/
    /* End of cleaning variable nd */
    } /*CHECKSCALAR(shape(komega, 0) == nk)*/
    } /*if (f2py_success) of nk*/
    /* End of cleaning variable nk */
    if((PyObject *)capi_darray_as_array!=darray_capi) {
        Py_XDECREF(capi_darray_as_array); }
    }  /* if (capi_darray_as_array == NULL) ... else of darray */
    /* End of cleaning variable darray */
    if((PyObject *)capi_vals_as_array!=vals_capi) {
        Py_XDECREF(capi_vals_as_array); }
    }  /* if (capi_vals_as_array == NULL) ... else of vals */
    /* End of cleaning variable vals */
    if((PyObject *)capi_nodes_as_array!=nodes_capi) {
        Py_XDECREF(capi_nodes_as_array); }
    }  /* if (capi_nodes_as_array == NULL) ... else of nodes */
    /* End of cleaning variable nodes */
    if((PyObject *)capi_komega_as_array!=komega_capi) {
        Py_XDECREF(capi_komega_as_array); }
    }  /* if (capi_komega_as_array == NULL) ... else of komega */
    /* End of cleaning variable komega */
    } /*if (f2py_success) of ns2*/
    /* End of cleaning variable ns2 */
    } /*if (f2py_success) of ns1*/
    /* End of cleaning variable ns1 */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/************************** end of compute_w_k_array **************************/

/******************************** compute_1_k ********************************/
static char doc_f2py_rout_sigwfast_sigwfast_mod_compute_1_k[] = "\
y_k = compute_1_k(nodes,vals,k,kernel,darray,ddarray,ssarray,nd,ns)\n\nWrapper for ``compute_1_k``.\
\n\nParameters\n----------\n"
"nodes : input rank-1 array('d') with bounds (f2py_nodes_d0)\n"
"vals : input rank-1 array('d') with bounds (f2py_vals_d0)\n"
"k : input float\n"
"kernel : input rank-1 array('d') with bounds (nd * ns)\n"
"darray : input rank-1 array('d') with bounds (nd)\n"
"ddarray : input rank-1 array('d') with bounds (nd * ns)\n"
"ssarray : input rank-1 array('d') with bounds (nd * ns)\n"
"nd : input int, optional\n    Default: shape(darray, 0)\n"
"ns : input int\n"
"\nReturns\n-------\n"
"y_k : float";
/* #declfortranroutine# */
static PyObject *f2py_rout_sigwfast_sigwfast_mod_compute_1_k(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,double*,double*,double*,double*,int*,int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double compute_1_kf2pywrap = 0;
    double *nodes = NULL;
    npy_intp nodes_Dims[1] = {-1};
    const int nodes_Rank = 1;
    PyArrayObject *capi_nodes_as_array = NULL;
    int capi_nodes_intent = 0;
    PyObject *nodes_capi = Py_None;
    double *vals = NULL;
    npy_intp vals_Dims[1] = {-1};
    const int vals_Rank = 1;
    PyArrayObject *capi_vals_as_array = NULL;
    int capi_vals_intent = 0;
    PyObject *vals_capi = Py_None;
    double k = 0;
    PyObject *k_capi = Py_None;
    double *kernel = NULL;
    npy_intp kernel_Dims[1] = {-1};
    const int kernel_Rank = 1;
    PyArrayObject *capi_kernel_as_array = NULL;
    int capi_kernel_intent = 0;
    PyObject *kernel_capi = Py_None;
    double *darray = NULL;
    npy_intp darray_Dims[1] = {-1};
    const int darray_Rank = 1;
    PyArrayObject *capi_darray_as_array = NULL;
    int capi_darray_intent = 0;
    PyObject *darray_capi = Py_None;
    double *ddarray = NULL;
    npy_intp ddarray_Dims[1] = {-1};
    const int ddarray_Rank = 1;
    PyArrayObject *capi_ddarray_as_array = NULL;
    int capi_ddarray_intent = 0;
    PyObject *ddarray_capi = Py_None;
    double *ssarray = NULL;
    npy_intp ssarray_Dims[1] = {-1};
    const int ssarray_Rank = 1;
    PyArrayObject *capi_ssarray_as_array = NULL;
    int capi_ssarray_intent = 0;
    PyObject *ssarray_capi = Py_None;
    int nd = 0;
    PyObject *nd_capi = Py_None;
    int ns = 0;
    PyObject *ns_capi = Py_None;
    int f2py_nodes_d0 = 0;
    int f2py_vals_d0 = 0;
    static char *capi_kwlist[] = {"nodes","vals","k","kernel","darray","ddarray","ssarray","nd","ns",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOOO|:sigwfast.sigwfast_mod.compute_1_k",\
        capi_kwlist,&nodes_capi,&vals_capi,&k_capi,&kernel_capi,&darray_capi,&ddarray_capi,&ssarray_capi,&nd_capi,&ns_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable ns */
        f2py_success = int_from_pyobj(&ns,ns_capi,"sigwfast.sigwfast_mod.compute_1_k() 9th argument (ns) can't be converted to int");
    if (f2py_success) {
    /* Processing variable k */
        f2py_success = double_from_pyobj(&k,k_capi,"sigwfast.sigwfast_mod.compute_1_k() 3rd argument (k) can't be converted to double");
    if (f2py_success) {
    /* Processing variable nodes */
    ;
    capi_nodes_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.compute_1_k: failed to create array from the 1st argument `nodes`";
    capi_nodes_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,nodes_Dims,nodes_Rank,  capi_nodes_intent,nodes_capi,capi_errmess);
    if (capi_nodes_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        nodes = (double *)(PyArray_DATA(capi_nodes_as_array));

    /* Processing variable vals */
    ;
    capi_vals_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.compute_1_k: failed to create array from the 2nd argument `vals`";
    capi_vals_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,vals_Dims,vals_Rank,  capi_vals_intent,vals_capi,capi_errmess);
    if (capi_vals_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        vals = (double *)(PyArray_DATA(capi_vals_as_array));

    /* Processing variable darray */
    ;
    capi_darray_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.compute_1_k: failed to create array from the 5th argument `darray`";
    capi_darray_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,darray_Dims,darray_Rank,  capi_darray_intent,darray_capi,capi_errmess);
    if (capi_darray_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        darray = (double *)(PyArray_DATA(capi_darray_as_array));

    /* Processing variable nd */
    if (nd_capi == Py_None) nd = shape(darray, 0); else
        f2py_success = int_from_pyobj(&nd,nd_capi,"sigwfast.sigwfast_mod.compute_1_k() 8th argument (nd) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(darray, 0) == nd,"shape(darray, 0) == nd","8th argument nd","compute_1_k:nd=%d",nd) {
    /* Processing variable kernel */
    kernel_Dims[0]=nd * ns;
    capi_kernel_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.compute_1_k: failed to create array from the 4th argument `kernel`";
    capi_kernel_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,kernel_Dims,kernel_Rank,  capi_kernel_intent,kernel_capi,capi_errmess);
    if (capi_kernel_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        kernel = (double *)(PyArray_DATA(capi_kernel_as_array));

    CHECKARRAY(shape(kernel, 0) == nd * ns,"shape(kernel, 0) == nd * ns","4th argument kernel") {
    CHECKARRAY(shape(kernel, 0) == nd * ns,"shape(kernel, 0) == nd * ns","4th argument kernel") {
    /* Processing variable ddarray */
    ddarray_Dims[0]=nd * ns;
    capi_ddarray_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.compute_1_k: failed to create array from the 6th argument `ddarray`";
    capi_ddarray_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,ddarray_Dims,ddarray_Rank,  capi_ddarray_intent,ddarray_capi,capi_errmess);
    if (capi_ddarray_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        ddarray = (double *)(PyArray_DATA(capi_ddarray_as_array));

    CHECKARRAY(shape(ddarray, 0) == nd * ns,"shape(ddarray, 0) == nd * ns","6th argument ddarray") {
    /* Processing variable ssarray */
    ssarray_Dims[0]=nd * ns;
    capi_ssarray_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.compute_1_k: failed to create array from the 7th argument `ssarray`";
    capi_ssarray_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,ssarray_Dims,ssarray_Rank,  capi_ssarray_intent,ssarray_capi,capi_errmess);
    if (capi_ssarray_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        ssarray = (double *)(PyArray_DATA(capi_ssarray_as_array));

    CHECKARRAY(shape(ssarray, 0) == nd * ns,"shape(ssarray, 0) == nd * ns","7th argument ssarray") {
    /* Processing variable compute_1_kf2pywrap */
    /* Processing variable f2py_nodes_d0 */
    f2py_nodes_d0 = shape(nodes, 0);
    /* Processing variable f2py_vals_d0 */
    f2py_vals_d0 = shape(vals, 0);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(&compute_1_kf2pywrap,nodes,vals,&k,kernel,darray,ddarray,ssarray,&nd,&ns,&f2py_nodes_d0,&f2py_vals_d0);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("d",compute_1_kf2pywrap);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable f2py_vals_d0 */
    /* End of cleaning variable f2py_nodes_d0 */
    /* End of cleaning variable compute_1_kf2pywrap */
    } /*CHECKARRAY(shape(ssarray, 0) == nd * ns)*/
    if((PyObject *)capi_ssarray_as_array!=ssarray_capi) {
        Py_XDECREF(capi_ssarray_as_array); }
    }  /* if (capi_ssarray_as_array == NULL) ... else of ssarray */
    /* End of cleaning variable ssarray */
    } /*CHECKARRAY(shape(ddarray, 0) == nd * ns)*/
    if((PyObject *)capi_ddarray_as_array!=ddarray_capi) {
        Py_XDECREF(capi_ddarray_as_array); }
    }  /* if (capi_ddarray_as_array == NULL) ... else of ddarray */
    /* End of cleaning variable ddarray */
    } /*CHECKARRAY(shape(kernel, 0) == nd * ns)*/
    } /*CHECKARRAY(shape(kernel, 0) == nd * ns)*/
    if((PyObject *)capi_kernel_as_array!=kernel_capi) {
        Py_XDECREF(capi_kernel_as_array); }
    }  /* if (capi_kernel_as_array == NULL) ... else of kernel */
    /* End of cleaning variable kernel */
    } /*CHECKSCALAR(shape(darray, 0) == nd)*/
    } /*if (f2py_success) of nd*/
    /* End of cleaning variable nd */
    if((PyObject *)capi_darray_as_array!=darray_capi) {
        Py_XDECREF(capi_darray_as_array); }
    }  /* if (capi_darray_as_array == NULL) ... else of darray */
    /* End of cleaning variable darray */
    if((PyObject *)capi_vals_as_array!=vals_capi) {
        Py_XDECREF(capi_vals_as_array); }
    }  /* if (capi_vals_as_array == NULL) ... else of vals */
    /* End of cleaning variable vals */
    if((PyObject *)capi_nodes_as_array!=nodes_capi) {
        Py_XDECREF(capi_nodes_as_array); }
    }  /* if (capi_nodes_as_array == NULL) ... else of nodes */
    /* End of cleaning variable nodes */
    } /*if (f2py_success) of k*/
    /* End of cleaning variable k */
    } /*if (f2py_success) of ns*/
    /* End of cleaning variable ns */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************************** end of compute_1_k *****************************/

/***************************** compute_1_k_array *****************************/
static char doc_f2py_rout_sigwfast_sigwfast_mod_compute_1_k_array[] = "\
integral = compute_1_k_array(nodes,vals,komega,kernel,darray,ddarray,ssarray,nd,ns,[nk])\n\nWrapper for ``compute_1_k_array``.\
\n\nParameters\n----------\n"
"nodes : input rank-1 array('d') with bounds (f2py_nodes_d0)\n"
"vals : input rank-1 array('d') with bounds (f2py_vals_d0)\n"
"komega : input rank-1 array('d') with bounds (nk)\n"
"kernel : input rank-1 array('d') with bounds (nd * ns)\n"
"darray : input rank-1 array('d') with bounds (nd)\n"
"ddarray : input rank-1 array('d') with bounds (nd * ns)\n"
"ssarray : input rank-1 array('d') with bounds (nd * ns)\n"
"nd : input int, optional\n    Default: shape(darray, 0)\n"
"ns : input int\n"
"\nOther Parameters\n----------------\n"
"nk : input int, optional\n    Default: shape(komega, 0)\n"
"\nReturns\n-------\n"
"integral : rank-1 array('d') with bounds (nk)";
/* #declfortranroutine# */
static PyObject *f2py_rout_sigwfast_sigwfast_mod_compute_1_k_array(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,int*,double*,double*,double*,double*,double*,int*,int*,double*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double *nodes = NULL;
    npy_intp nodes_Dims[1] = {-1};
    const int nodes_Rank = 1;
    PyArrayObject *capi_nodes_as_array = NULL;
    int capi_nodes_intent = 0;
    PyObject *nodes_capi = Py_None;
    double *vals = NULL;
    npy_intp vals_Dims[1] = {-1};
    const int vals_Rank = 1;
    PyArrayObject *capi_vals_as_array = NULL;
    int capi_vals_intent = 0;
    PyObject *vals_capi = Py_None;
    int nk = 0;
    PyObject *nk_capi = Py_None;
    double *komega = NULL;
    npy_intp komega_Dims[1] = {-1};
    const int komega_Rank = 1;
    PyArrayObject *capi_komega_as_array = NULL;
    int capi_komega_intent = 0;
    PyObject *komega_capi = Py_None;
    double *kernel = NULL;
    npy_intp kernel_Dims[1] = {-1};
    const int kernel_Rank = 1;
    PyArrayObject *capi_kernel_as_array = NULL;
    int capi_kernel_intent = 0;
    PyObject *kernel_capi = Py_None;
    double *darray = NULL;
    npy_intp darray_Dims[1] = {-1};
    const int darray_Rank = 1;
    PyArrayObject *capi_darray_as_array = NULL;
    int capi_darray_intent = 0;
    PyObject *darray_capi = Py_None;
    double *ddarray = NULL;
    npy_intp ddarray_Dims[1] = {-1};
    const int ddarray_Rank = 1;
    PyArrayObject *capi_ddarray_as_array = NULL;
    int capi_ddarray_intent = 0;
    PyObject *ddarray_capi = Py_None;
    double *ssarray = NULL;
    npy_intp ssarray_Dims[1] = {-1};
    const int ssarray_Rank = 1;
    PyArrayObject *capi_ssarray_as_array = NULL;
    int capi_ssarray_intent = 0;
    PyObject *ssarray_capi = Py_None;
    int nd = 0;
    PyObject *nd_capi = Py_None;
    int ns = 0;
    PyObject *ns_capi = Py_None;
    double *integral = NULL;
    npy_intp integral_Dims[1] = {-1};
    const int integral_Rank = 1;
    PyArrayObject *capi_integral_as_array = NULL;
    int capi_integral_intent = 0;
    int f2py_nodes_d0 = 0;
    int f2py_vals_d0 = 0;
    static char *capi_kwlist[] = {"nodes","vals","komega","kernel","darray","ddarray","ssarray","nd","ns","nk",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOOO|O:sigwfast.sigwfast_mod.compute_1_k_array",\
        capi_kwlist,&nodes_capi,&vals_capi,&komega_capi,&kernel_capi,&darray_capi,&ddarray_capi,&ssarray_capi,&nd_capi,&ns_capi,&nk_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable ns */
        f2py_success = int_from_pyobj(&ns,ns_capi,"sigwfast.sigwfast_mod.compute_1_k_array() 9th argument (ns) can't be converted to int");
    if (f2py_success) {
    /* Processing variable nodes */
    ;
    capi_nodes_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.compute_1_k_array: failed to create array from the 1st argument `nodes`";
    capi_nodes_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,nodes_Dims,nodes_Rank,  capi_nodes_intent,nodes_capi,capi_errmess);
    if (capi_nodes_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        nodes = (double *)(PyArray_DATA(capi_nodes_as_array));

    /* Processing variable vals */
    ;
    capi_vals_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.compute_1_k_array: failed to create array from the 2nd argument `vals`";
    capi_vals_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,vals_Dims,vals_Rank,  capi_vals_intent,vals_capi,capi_errmess);
    if (capi_vals_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        vals = (double *)(PyArray_DATA(capi_vals_as_array));

    /* Processing variable komega */
    ;
    capi_komega_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.compute_1_k_array: failed to create array from the 3rd argument `komega`";
    capi_komega_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,komega_Dims,komega_Rank,  capi_komega_intent,komega_capi,capi_errmess);
    if (capi_komega_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        komega = (double *)(PyArray_DATA(capi_komega_as_array));

    /* Processing variable darray */
    ;
    capi_darray_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.compute_1_k_array: failed to create array from the 5th argument `darray`";
    capi_darray_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,darray_Dims,darray_Rank,  capi_darray_intent,darray_capi,capi_errmess);
    if (capi_darray_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        darray = (double *)(PyArray_DATA(capi_darray_as_array));

    /* Processing variable nk */
    if (nk_capi == Py_None) nk = shape(komega, 0); else
        f2py_success = int_from_pyobj(&nk,nk_capi,"sigwfast.sigwfast_mod.compute_1_k_array() 1st keyword (nk) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(komega, 0) == nk,"shape(komega, 0) == nk","1st keyword nk","compute_1_k_array:nk=%d",nk) {
    /* Processing variable nd */
    if (nd_capi == Py_None) nd = shape(darray, 0); else
        f2py_success = int_from_pyobj(&nd,nd_capi,"sigwfast.sigwfast_mod.compute_1_k_array() 8th argument (nd) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(darray, 0) == nd,"shape(darray, 0) == nd","8th argument nd","compute_1_k_array:nd=%d",nd) {
    /* Processing variable kernel */
    kernel_Dims[0]=nd * ns;
    capi_kernel_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.compute_1_k_array: failed to create array from the 4th argument `kernel`";
    capi_kernel_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,kernel_Dims,kernel_Rank,  capi_kernel_intent,kernel_capi,capi_errmess);
    if (capi_kernel_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        kernel = (double *)(PyArray_DATA(capi_kernel_as_array));

    CHECKARRAY(shape(kernel, 0) == nd * ns,"shape(kernel, 0) == nd * ns","4th argument kernel") {
    CHECKARRAY(shape(kernel, 0) == nd * ns,"shape(kernel, 0) == nd * ns","4th argument kernel") {
    /* Processing variable ddarray */
    ddarray_Dims[0]=nd * ns;
    capi_ddarray_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.compute_1_k_array: failed to create array from the 6th argument `ddarray`";
    capi_ddarray_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,ddarray_Dims,ddarray_Rank,  capi_ddarray_intent,ddarray_capi,capi_errmess);
    if (capi_ddarray_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        ddarray = (double *)(PyArray_DATA(capi_ddarray_as_array));

    CHECKARRAY(shape(ddarray, 0) == nd * ns,"shape(ddarray, 0) == nd * ns","6th argument ddarray") {
    /* Processing variable ssarray */
    ssarray_Dims[0]=nd * ns;
    capi_ssarray_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.compute_1_k_array: failed to create array from the 7th argument `ssarray`";
    capi_ssarray_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,ssarray_Dims,ssarray_Rank,  capi_ssarray_intent,ssarray_capi,capi_errmess);
    if (capi_ssarray_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        ssarray = (double *)(PyArray_DATA(capi_ssarray_as_array));

    CHECKARRAY(shape(ssarray, 0) == nd * ns,"shape(ssarray, 0) == nd * ns","7th argument ssarray") {
    /* Processing variable integral */
    integral_Dims[0]=nk;
    capi_integral_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char * capi_errmess = "sigwfast.sigwfast.sigwfast_mod.compute_1_k_array: failed to create array from the hidden `integral`";
    capi_integral_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,integral_Dims,integral_Rank,  capi_integral_intent,Py_None,capi_errmess);
    if (capi_integral_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = sigwfast_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        integral = (double *)(PyArray_DATA(capi_integral_as_array));

    /* Processing variable f2py_nodes_d0 */
    f2py_nodes_d0 = shape(nodes, 0);
    /* Processing variable f2py_vals_d0 */
    f2py_vals_d0 = shape(vals, 0);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(nodes,vals,&nk,komega,kernel,darray,ddarray,ssarray,&nd,&ns,integral,&f2py_nodes_d0,&f2py_vals_d0);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_integral_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable f2py_vals_d0 */
    /* End of cleaning variable f2py_nodes_d0 */
    }  /* if (capi_integral_as_array == NULL) ... else of integral */
    /* End of cleaning variable integral */
    } /*CHECKARRAY(shape(ssarray, 0) == nd * ns)*/
    if((PyObject *)capi_ssarray_as_array!=ssarray_capi) {
        Py_XDECREF(capi_ssarray_as_array); }
    }  /* if (capi_ssarray_as_array == NULL) ... else of ssarray */
    /* End of cleaning variable ssarray */
    } /*CHECKARRAY(shape(ddarray, 0) == nd * ns)*/
    if((PyObject *)capi_ddarray_as_array!=ddarray_capi) {
        Py_XDECREF(capi_ddarray_as_array); }
    }  /* if (capi_ddarray_as_array == NULL) ... else of ddarray */
    /* End of cleaning variable ddarray */
    } /*CHECKARRAY(shape(kernel, 0) == nd * ns)*/
    } /*CHECKARRAY(shape(kernel, 0) == nd * ns)*/
    if((PyObject *)capi_kernel_as_array!=kernel_capi) {
        Py_XDECREF(capi_kernel_as_array); }
    }  /* if (capi_kernel_as_array == NULL) ... else of kernel */
    /* End of cleaning variable kernel */
    } /*CHECKSCALAR(shape(darray, 0) == nd)*/
    } /*if (f2py_success) of nd*/
    /* End of cleaning variable nd */
    } /*CHECKSCALAR(shape(komega, 0) == nk)*/
    } /*if (f2py_success) of nk*/
    /* End of cleaning variable nk */
    if((PyObject *)capi_darray_as_array!=darray_capi) {
        Py_XDECREF(capi_darray_as_array); }
    }  /* if (capi_darray_as_array == NULL) ... else of darray */
    /* End of cleaning variable darray */
    if((PyObject *)capi_komega_as_array!=komega_capi) {
        Py_XDECREF(capi_komega_as_array); }
    }  /* if (capi_komega_as_array == NULL) ... else of komega */
    /* End of cleaning variable komega */
    if((PyObject *)capi_vals_as_array!=vals_capi) {
        Py_XDECREF(capi_vals_as_array); }
    }  /* if (capi_vals_as_array == NULL) ... else of vals */
    /* End of cleaning variable vals */
    if((PyObject *)capi_nodes_as_array!=nodes_capi) {
        Py_XDECREF(capi_nodes_as_array); }
    }  /* if (capi_nodes_as_array == NULL) ... else of nodes */
    /* End of cleaning variable nodes */
    } /*if (f2py_success) of ns*/
    /* End of cleaning variable ns */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/************************** end of compute_1_k_array **************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/

static FortranDataDef f2py_precision_mod_def[] = {
  {"dp",0,{{-1}},NPY_INT, 1},
  {NULL}
};

static void f2py_setup_precision_mod(char *dp) {
  int i_f2py=0;
  f2py_precision_mod_def[i_f2py++].data = dp;
}
extern void F_FUNC_US(f2pyinitprecision_mod,F2PYINITPRECISION_MOD)(void (*)(char*));
static void f2py_init_precision_mod(void) {
  F_FUNC_US(f2pyinitprecision_mod,F2PYINITPRECISION_MOD)(f2py_setup_precision_mod);
}


static FortranDataDef f2py_constants_mod_def[] = {
  {"pi",0,{{-1}},NPY_DOUBLE, 1},
  {"c",0,{{-1}},NPY_DOUBLE, 1},
  {"mpc",0,{{-1}},NPY_DOUBLE, 1},
  {"mpc_in_sec",0,{{-1}},NPY_DOUBLE, 1},
  {NULL}
};

static void f2py_setup_constants_mod(char *pi,char *c,char *mpc,char *mpc_in_sec) {
  int i_f2py=0;
  f2py_constants_mod_def[i_f2py++].data = pi;
  f2py_constants_mod_def[i_f2py++].data = c;
  f2py_constants_mod_def[i_f2py++].data = mpc;
  f2py_constants_mod_def[i_f2py++].data = mpc_in_sec;
}
extern void F_FUNC_US(f2pyinitconstants_mod,F2PYINITCONSTANTS_MOD)(void (*)(char*,char*,char*,char*));
static void f2py_init_constants_mod(void) {
  F_FUNC_US(f2pyinitconstants_mod,F2PYINITCONSTANTS_MOD)(f2py_setup_constants_mod);
}


static FortranDataDef f2py_sigwfast_mod_def[] = {
  {"power_spectrum_k",-1,{{-1}},0,0,NULL,(void *)f2py_rout_sigwfast_sigwfast_mod_power_spectrum_k,doc_f2py_rout_sigwfast_sigwfast_mod_power_spectrum_k},
  {"power_spectrum_k_array",-1,{{-1}},0,0,NULL,(void *)f2py_rout_sigwfast_sigwfast_mod_power_spectrum_k_array,doc_f2py_rout_sigwfast_sigwfast_mod_power_spectrum_k_array},
  {"psquared",-1,{{-1}},0,0,NULL,(void *)f2py_rout_sigwfast_sigwfast_mod_psquared,doc_f2py_rout_sigwfast_sigwfast_mod_psquared},
  {"compute_w_k",-1,{{-1}},0,0,NULL,(void *)f2py_rout_sigwfast_sigwfast_mod_compute_w_k,doc_f2py_rout_sigwfast_sigwfast_mod_compute_w_k},
  {"compute_w_k_array",-1,{{-1}},0,0,NULL,(void *)f2py_rout_sigwfast_sigwfast_mod_compute_w_k_array,doc_f2py_rout_sigwfast_sigwfast_mod_compute_w_k_array},
  {"compute_1_k",-1,{{-1}},0,0,NULL,(void *)f2py_rout_sigwfast_sigwfast_mod_compute_1_k,doc_f2py_rout_sigwfast_sigwfast_mod_compute_1_k},
  {"compute_1_k_array",-1,{{-1}},0,0,NULL,(void *)f2py_rout_sigwfast_sigwfast_mod_compute_1_k_array,doc_f2py_rout_sigwfast_sigwfast_mod_compute_1_k_array},
  {NULL}
};

static void f2py_setup_sigwfast_mod(char *power_spectrum_k,char *power_spectrum_k_array,char *psquared,char *compute_w_k,char *compute_w_k_array,char *compute_1_k,char *compute_1_k_array) {
  int i_f2py=0;
  f2py_sigwfast_mod_def[i_f2py++].data = power_spectrum_k;
  f2py_sigwfast_mod_def[i_f2py++].data = power_spectrum_k_array;
  f2py_sigwfast_mod_def[i_f2py++].data = psquared;
  f2py_sigwfast_mod_def[i_f2py++].data = compute_w_k;
  f2py_sigwfast_mod_def[i_f2py++].data = compute_w_k_array;
  f2py_sigwfast_mod_def[i_f2py++].data = compute_1_k;
  f2py_sigwfast_mod_def[i_f2py++].data = compute_1_k_array;
}
extern void F_FUNC_US(f2pyinitsigwfast_mod,F2PYINITSIGWFAST_MOD)(void (*)(char *,char *,char *,char *,char *,char *,char *));
static void f2py_init_sigwfast_mod(void) {
  F_FUNC_US(f2pyinitsigwfast_mod,F2PYINITSIGWFAST_MOD)(f2py_setup_sigwfast_mod);
}

/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "sigwfast",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit_sigwfast(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = sigwfast_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module sigwfast (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("1.26.4");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module 'sigwfast' is auto-generated with f2py (version:1.26.4).\nFunctions:\n"
"Fortran 90/95 modules:\n""  precision_mod --- dp""  constants_mod --- pi,c,mpc,mpc_in_sec""  sigwfast_mod --- power_spectrum_k(),power_spectrum_k_array(),psquared(),compute_w_k(),compute_w_k_array(),compute_1_k(),compute_1_k_array()"".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("1.26.4");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    sigwfast_error = PyErr_NewException ("sigwfast.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "_sigwfast_error", sigwfast_error);
    Py_DECREF(sigwfast_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }







/*eof initf2pywraphooks*/
  PyDict_SetItemString(d, "sigwfast_mod", PyFortranObject_New(f2py_sigwfast_mod_def,f2py_init_sigwfast_mod));
  PyDict_SetItemString(d, "constants_mod", PyFortranObject_New(f2py_constants_mod_def,f2py_init_constants_mod));
  PyDict_SetItemString(d, "precision_mod", PyFortranObject_New(f2py_precision_mod_def,f2py_init_precision_mod));
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"sigwfast");
#endif
    return m;
}
#ifdef __cplusplus
}
#endif
