!     -*- f90 -*-
!     This file is autogenerated with f2py (version:1.26.4)
!     It contains Fortran 90 wrappers to fortran functions.

      
      subroutine f2pyinitprecision_mod(f2pysetupfunc)
      use precision_mod, only : dp
      external f2pysetupfunc
      call f2pysetupfunc(dp)
      end subroutine f2pyinitprecision_mod

      
      subroutine f2pyinitconstants_mod(f2pysetupfunc)
      use constants_mod, only : pi
      use constants_mod, only : c
      use constants_mod, only : mpc
      use constants_mod, only : mpc_in_sec
      external f2pysetupfunc
      call f2pysetupfunc(pi,c,mpc,mpc_in_sec)
      end subroutine f2pyinitconstants_mod

      subroutine f2pywrap_sigwfast_mod_power_spectrum_k (power_spectrum_&
     &kf2pywrap, nodes, vals, k, f2py_nodes_d0, f2py_vals_d0)
      use sigwfast_mod, only : power_spectrum_k
      real(kind=8) k
      integer f2py_nodes_d0
      integer f2py_vals_d0
      real(kind=8) nodes(f2py_nodes_d0)
      real(kind=8) vals(f2py_vals_d0)
      real(kind=8) power_spectrum_kf2pywrap
      power_spectrum_kf2pywrap = power_spectrum_k(nodes, vals, k)
      end subroutine f2pywrap_sigwfast_mod_power_spectrum_k
      subroutine f2pywrap_sigwfast_mod_power_spectrum_k_array (power_spe&
     &ctrum_k_arrayf2pywrap, nodes, vals, k, f2py_nodes_d0, f2py_vals_d0&
     &, f2py_k_d0)
      use sigwfast_mod, only : power_spectrum_k_array
      integer f2py_nodes_d0
      integer f2py_vals_d0
      integer f2py_k_d0
      real(kind=8) nodes(f2py_nodes_d0)
      real(kind=8) vals(f2py_vals_d0)
      real(kind=8) k(f2py_k_d0)
      real(kind=8) power_spectrum_k_arrayf2pywrap(size(k))
      power_spectrum_k_arrayf2pywrap = power_spectrum_k_array(nodes, val&
     &s, k)
      end subroutine f2pywrap_sigwfast_mod_power_spectrum_k_array
      subroutine f2pywrap_sigwfast_mod_psquared (psquaredf2pywrap, nodes&
     &, vals, d, s, k, f2py_nodes_d0, f2py_vals_d0, f2py_d_d0, f2py_s_d0&
     &)
      use sigwfast_mod, only : psquared
      real(kind=8) k
      integer f2py_nodes_d0
      integer f2py_vals_d0
      integer f2py_d_d0
      integer f2py_s_d0
      real(kind=8) nodes(f2py_nodes_d0)
      real(kind=8) vals(f2py_vals_d0)
      real(kind=8) d(f2py_d_d0)
      real(kind=8) s(f2py_s_d0)
      real(kind=8) psquaredf2pywrap(size(d))
      psquaredf2pywrap = psquared(nodes, vals, d, s, k)
      end subroutine f2pywrap_sigwfast_mod_psquared
      subroutine f2pywrap_sigwfast_mod_compute_w_k (compute_w_kf2pywrap,&
     & nodes, vals, k, kernel1, kernel2, d1array, s1array, d2array, s2ar&
     &ray, darray, nd, ns1, ns2, f2py_nodes_d0, f2py_vals_d0)
      use sigwfast_mod, only : compute_w_k
      real(kind=8) k
      integer nd
      integer ns1
      integer ns2
      integer f2py_nodes_d0
      integer f2py_vals_d0
      real(kind=8) nodes(f2py_nodes_d0)
      real(kind=8) vals(f2py_vals_d0)
      real(kind=8) kernel1(nd * ns1)
      real(kind=8) kernel2(nd * ns2)
      real(kind=8) d1array(nd * ns1)
      real(kind=8) s1array(nd * ns1)
      real(kind=8) d2array(nd * ns2)
      real(kind=8) s2array(nd * ns2)
      real(kind=8) darray(nd)
      real(kind=8) compute_w_kf2pywrap
      compute_w_kf2pywrap = compute_w_k(nodes, vals, k, kernel1, kernel2&
     &, d1array, s1array, d2array, s2array, darray, nd, ns1, ns2)
      end subroutine f2pywrap_sigwfast_mod_compute_w_k
      subroutine f2pywrap_sigwfast_mod_compute_w_k_array (nodes, vals, n&
     &k, komega, kernel1, kernel2, d1array, s1array, d2array, s2array, d&
     &array, nd, ns1, ns2, integral, f2py_nodes_d0, f2py_vals_d0)
      use sigwfast_mod, only : compute_w_k_array
      integer nk
      integer nd
      integer ns1
      integer ns2
      integer f2py_nodes_d0
      integer f2py_vals_d0
      real(kind=8) nodes(f2py_nodes_d0)
      real(kind=8) vals(f2py_vals_d0)
      real(kind=8) komega(nk)
      real(kind=8) kernel1(nd * ns1)
      real(kind=8) kernel2(nd * ns2)
      real(kind=8) d1array(nd * ns1)
      real(kind=8) s1array(nd * ns1)
      real(kind=8) d2array(nd * ns2)
      real(kind=8) s2array(nd * ns2)
      real(kind=8) darray(nd)
      real(kind=8) integral(nk)
      call compute_w_k_array(nodes, vals, nk, komega, kernel1, kernel2, &
     &d1array, s1array, d2array, s2array, darray, nd, ns1, ns2, integral&
     &)
      end subroutine f2pywrap_sigwfast_mod_compute_w_k_array
      subroutine f2pywrap_sigwfast_mod_compute_1_k (compute_1_kf2pywrap,&
     & nodes, vals, k, kernel, darray, ddarray, ssarray, nd, ns, f2py_no&
     &des_d0, f2py_vals_d0)
      use sigwfast_mod, only : compute_1_k
      real(kind=8) k
      integer nd
      integer ns
      integer f2py_nodes_d0
      integer f2py_vals_d0
      real(kind=8) nodes(f2py_nodes_d0)
      real(kind=8) vals(f2py_vals_d0)
      real(kind=8) kernel(nd * ns)
      real(kind=8) darray(nd)
      real(kind=8) ddarray(nd * ns)
      real(kind=8) ssarray(nd * ns)
      real(kind=8) compute_1_kf2pywrap
      compute_1_kf2pywrap = compute_1_k(nodes, vals, k, kernel, darray, &
     &ddarray, ssarray, nd, ns)
      end subroutine f2pywrap_sigwfast_mod_compute_1_k
      subroutine f2pywrap_sigwfast_mod_compute_1_k_array (nodes, vals, n&
     &k, komega, kernel, darray, ddarray, ssarray, nd, ns, integral, f2p&
     &y_nodes_d0, f2py_vals_d0)
      use sigwfast_mod, only : compute_1_k_array
      integer nk
      integer nd
      integer ns
      integer f2py_nodes_d0
      integer f2py_vals_d0
      real(kind=8) nodes(f2py_nodes_d0)
      real(kind=8) vals(f2py_vals_d0)
      real(kind=8) komega(nk)
      real(kind=8) kernel(nd * ns)
      real(kind=8) darray(nd)
      real(kind=8) ddarray(nd * ns)
      real(kind=8) ssarray(nd * ns)
      real(kind=8) integral(nk)
      call compute_1_k_array(nodes, vals, nk, komega, kernel, darray, dd&
     &array, ssarray, nd, ns, integral)
      end subroutine f2pywrap_sigwfast_mod_compute_1_k_array
      
      subroutine f2pyinitsigwfast_mod(f2pysetupfunc)
      interface 
      subroutine f2pywrap_sigwfast_mod_power_spectrum_k (power_spectrum_&
     &kf2pywrap, nodes, vals, k, f2py_nodes_d0, f2py_vals_d0)
      real(kind=8) k
      integer f2py_nodes_d0
      integer f2py_vals_d0
      real(kind=8) nodes(f2py_nodes_d0)
      real(kind=8) vals(f2py_vals_d0)
      real(kind=8) power_spectrum_kf2pywrap
      end subroutine f2pywrap_sigwfast_mod_power_spectrum_k 
      subroutine f2pywrap_sigwfast_mod_power_spectrum_k_array (power_spe&
     &ctrum_k_arrayf2pywrap, nodes, vals, k, f2py_nodes_d0, f2py_vals_d0&
     &, f2py_k_d0)
      integer f2py_nodes_d0
      integer f2py_vals_d0
      integer f2py_k_d0
      real(kind=8) nodes(f2py_nodes_d0)
      real(kind=8) vals(f2py_vals_d0)
      real(kind=8) k(f2py_k_d0)
      real(kind=8) power_spectrum_k_arrayf2pywrap(size(k))
      end subroutine f2pywrap_sigwfast_mod_power_spectrum_k_array 
      subroutine f2pywrap_sigwfast_mod_psquared (psquaredf2pywrap, nodes&
     &, vals, d, s, k, f2py_nodes_d0, f2py_vals_d0, f2py_d_d0, f2py_s_d0&
     &)
      real(kind=8) k
      integer f2py_nodes_d0
      integer f2py_vals_d0
      integer f2py_d_d0
      integer f2py_s_d0
      real(kind=8) nodes(f2py_nodes_d0)
      real(kind=8) vals(f2py_vals_d0)
      real(kind=8) d(f2py_d_d0)
      real(kind=8) s(f2py_s_d0)
      real(kind=8) psquaredf2pywrap(size(d))
      end subroutine f2pywrap_sigwfast_mod_psquared 
      subroutine f2pywrap_sigwfast_mod_compute_w_k (compute_w_kf2pywrap,&
     & nodes, vals, k, kernel1, kernel2, d1array, s1array, d2array, s2ar&
     &ray, darray, nd, ns1, ns2, f2py_nodes_d0, f2py_vals_d0)
      real(kind=8) k
      integer nd
      integer ns1
      integer ns2
      integer f2py_nodes_d0
      integer f2py_vals_d0
      real(kind=8) nodes(f2py_nodes_d0)
      real(kind=8) vals(f2py_vals_d0)
      real(kind=8) kernel1(nd * ns1)
      real(kind=8) kernel2(nd * ns2)
      real(kind=8) d1array(nd * ns1)
      real(kind=8) s1array(nd * ns1)
      real(kind=8) d2array(nd * ns2)
      real(kind=8) s2array(nd * ns2)
      real(kind=8) darray(nd)
      real(kind=8) compute_w_kf2pywrap
      end subroutine f2pywrap_sigwfast_mod_compute_w_k 
      subroutine f2pywrap_sigwfast_mod_compute_w_k_array (nodes, vals, n&
     &k, komega, kernel1, kernel2, d1array, s1array, d2array, s2array, d&
     &array, nd, ns1, ns2, integral, f2py_nodes_d0, f2py_vals_d0)
      integer nk
      integer nd
      integer ns1
      integer ns2
      integer f2py_nodes_d0
      integer f2py_vals_d0
      real(kind=8) nodes(f2py_nodes_d0)
      real(kind=8) vals(f2py_vals_d0)
      real(kind=8) komega(nk)
      real(kind=8) kernel1(nd * ns1)
      real(kind=8) kernel2(nd * ns2)
      real(kind=8) d1array(nd * ns1)
      real(kind=8) s1array(nd * ns1)
      real(kind=8) d2array(nd * ns2)
      real(kind=8) s2array(nd * ns2)
      real(kind=8) darray(nd)
      real(kind=8) integral(nk)
      end subroutine f2pywrap_sigwfast_mod_compute_w_k_array 
      subroutine f2pywrap_sigwfast_mod_compute_1_k (compute_1_kf2pywrap,&
     & nodes, vals, k, kernel, darray, ddarray, ssarray, nd, ns, f2py_no&
     &des_d0, f2py_vals_d0)
      real(kind=8) k
      integer nd
      integer ns
      integer f2py_nodes_d0
      integer f2py_vals_d0
      real(kind=8) nodes(f2py_nodes_d0)
      real(kind=8) vals(f2py_vals_d0)
      real(kind=8) kernel(nd * ns)
      real(kind=8) darray(nd)
      real(kind=8) ddarray(nd * ns)
      real(kind=8) ssarray(nd * ns)
      real(kind=8) compute_1_kf2pywrap
      end subroutine f2pywrap_sigwfast_mod_compute_1_k 
      subroutine f2pywrap_sigwfast_mod_compute_1_k_array (nodes, vals, n&
     &k, komega, kernel, darray, ddarray, ssarray, nd, ns, integral, f2p&
     &y_nodes_d0, f2py_vals_d0)
      integer nk
      integer nd
      integer ns
      integer f2py_nodes_d0
      integer f2py_vals_d0
      real(kind=8) nodes(f2py_nodes_d0)
      real(kind=8) vals(f2py_vals_d0)
      real(kind=8) komega(nk)
      real(kind=8) kernel(nd * ns)
      real(kind=8) darray(nd)
      real(kind=8) ddarray(nd * ns)
      real(kind=8) ssarray(nd * ns)
      real(kind=8) integral(nk)
      end subroutine f2pywrap_sigwfast_mod_compute_1_k_array
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(f2pywrap_sigwfast_mod_power_spectrum_k,f2pywrap&
     &_sigwfast_mod_power_spectrum_k_array,f2pywrap_sigwfast_mod_psquare&
     &d,f2pywrap_sigwfast_mod_compute_w_k,f2pywrap_sigwfast_mod_compute_&
     &w_k_array,f2pywrap_sigwfast_mod_compute_1_k,f2pywrap_sigwfast_mod_&
     &compute_1_k_array)
      end subroutine f2pyinitsigwfast_mod


